### ISSUE TITLE
ConcurrentModificationException while date upcomes

### ISSUE THREAD

**Issue by EzzPress** [patrykandpatryk/vico#149]
Hello, I'm plotting upcoming data, single series, 1-10 dots per second in linechart style.
Sometimes the app execution crashes with

```
FATAL EXCEPTION: pool-3-thread-3

java.util.ConcurrentModificationException

at java.util.ArrayList$Itr.next(ArrayList.java:860)
--
at com.patrykandpatryk.vico.core.entry.diff.DefaultDiffProcessor.updateProgressMap(DefaultDiffProcessor.kt:220)
at com.patrykandpatryk.vico.core.entry.diff.DefaultDiffProcessor.setEntries(DefaultDiffProcessor.kt:50)
at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.setEntries$lambda$1$lambda$0(ChartEntryModelProducer.kt:73)
at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.$r8$lambda$ouCUkSdPZbczQqr-7snrCS2u75g(Unknown Source:0)
at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer$ExternalSyntheticLambda0.run(Unknown Source:4)
```
It doesn't depend on presence of markers, or the data size, or running-up time. It is random event

I use the viewmodel pattern, producer and entries are in viewmodel, the composable uses viewmodel.producer to construct the chart

**Comment by patrykmichalik** [comment]
Hello! Would you be able to provide a minimal reproducible example?

**Comment by EzzPress** [comment]
I discover little bit more, so when I put data successively and the two neighbor dots have the same X-value, I got crash

**Comment by Gowsky** [comment]
> I discover little bit more, so when I put data successively and the two neighbor dots have the same X-value, I got crash

That's actually expected. You can't have multiple entries for single x-axis value in a single list. You need to add another list of entries for that.
