### ISSUE TITLE
Concurrent exception when values emitting is too fast

### ISSUE THREAD

**Issue by permiakover** [patrykandpatryk/vico#165]
Hi, i have the issue when the async incoming data arrive to fast (during 1 ms).
` FATAL EXCEPTION: pool-10-thread-1
                                                                                                    Process: 
                                                                                                    java.util.ConcurrentModificationException
                                                                                                    	at java.util.ArrayList$Itr.next(ArrayList.java:860)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.diff.DefaultDiffProcessor.updateProgressMap(DefaultDiffProcessor.kt:220)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.diff.DefaultDiffProcessor.setEntries(DefaultDiffProcessor.kt:50)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.setEntries$lambda$1$lambda$0(ChartEntryModelProducer.kt:73)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer.$r8$lambda$ouCUkSdPZbczQqr-7snrCS2u75g(Unknown Source:0)
                                                                                                    	at com.patrykandpatryk.vico.core.entry.ChartEntryModelProducer$$ExternalSyntheticLambda0.run(Unknown Source:4)`

I have 300-500 dots of line chart on a screen, and i update the chart entry on every new dot. And the way of such chart update seems to be not thread-safe.
Is there any way of synchronization inside of ChartEntryModelProducer?

**Comment by patrykmichalik** [comment]
Hello! Thanks for the report. Would you be able to provide a minimal reproducible example?

**Comment by permiakover** [comment]
Yes, something like that. In the first state I have 300 dots (x,y), plot, on next iteration I got 3 new values should be added to the right. I change my entry list and set entries to the producer. last entry list and new entry list have intersections of course, so if this is wrong way of updating chart on upcoming values, so what is correct way?

**Comment by patrykmichalik** [comment]
It’s not an issue for the old and new data sets to have overlaps. This is, of course, almost always necessary. I’ve tried to reproduce the issue in question, but unfortunately, I can’t seem to trigger the crash. Could you update your code such that whenever `setEntries` is called, the data set (or data sets) passed to the function and the time at which the function is called are logged to the console, and then share the logs here? Cheers!

**Comment by permiakover** [comment]
yes, the trigger it seems very random, i got one per 15-30 minutes of work, even try-catch and single-thread-dispatcher couldn't fix it.
From my point of experience the UI-part somethings couldn't handle new values when it is in handling previous to draw. this situation was in desktop version at JFreechart.
Any way I'm curious about the crash, and will try to reproduce the crash

**Comment by permiakover** [comment]
> It’s not an issue for the old and new data sets to have overlaps. This is, of course, almost always necessary. I’ve tried to reproduce the issue in question, but unfortunately, I can’t seem to trigger the crash. Could you update your code such that whenever `setEntries` is called, the data set passed to the function (specifically, the coordinates of each entry) and the time at which the function is called are logged, and then share the logs here? Cheers!

The project mentioned in #145 could reproduce the issue, if you set the delay between emitions below 10 ms
Should be mentioned that if there are entries with a single float entry, chart runs fine even with 1ms delay

**Comment by patrykmichalik** [comment]
Thanks for the update! I’ve been able to reproduce the issue.

**Comment by patrickmichalik** [comment]
Vico 1.6.1, which is now rolling out, resolves the bug in question. Consequently, I’ll be closing this issue. Thanks for the report!
